import csv
import sys
import os

# Function to check if the path is a valid file
def is_valid_file(path):
    return os.path.isfile(path) and path.endswith('.csv')

# Function to check if the path is a valid path for writing
def is_valid_output_path(path):
    # Check if the path ends with '.csv'
    if not path.endswith('.csv'):
        return False
    # Check if the directory of the path exists, if not, it's not a valid output path
    directory = os.path.dirname(path)
    return os.path.exists(directory) if directory else True

# Function to check if the directory of the output path exists or if the path is at the root directory
def is_valid_output_directory(path):
    directory = os.path.dirname(path)
    # If there's no directory part, we assume current directory which is valid
    return os.path.exists(directory) or not directory

input_csv = sys.argv[1] if len(sys.argv) > 1 else None
invoices_csv = sys.argv[2] if len(sys.argv) > 2 else None

# Check if both arguments were provided
if not input_csv or not invoices_csv:
    print("Error: Both input and output CSV paths must be provided.")
    sys.exit(1)

# Check if the input CSV path is valid
if not is_valid_file(input_csv):
    print(f"Error: The input CSV path '{input_csv}' is not a valid file.")
    sys.exit(1)


# Check if the directory for the output CSV is valid
if not is_valid_output_directory(invoices_csv):
    print(f"Error: The directory for the output CSV path '{invoices_csv}' does not exist.")
    sys.exit(1)
# Check if the directory for the output CSV is valid

product_map = {
    'Bacon Egg and Cheese': 2,
    'Chicken Tender Box': 31,
    'Original Chicken Biscuit': 1,
    'Combo Meal': 44,
    'Bundaberg': 43,
    'Soda': 42,
    'Sweet Tea': 41,
    'Fries': 4,
    'Biscuit': 3,
    'Chicken Tenders': 32,
}

customer_type = {
    'Dine In': 14,
    'take out': 15,
}

bank_account = {
    'line pay(LINE Pay physical store payment module)': 3,
    'Cash(Cash payment module)': 2,
}

blank_invoice = {
    "module": None,
    "entity": "1",
    "import_key": None,
    "array_options": [],
    "array_languages": None,
    "contacts_ids": [],
    "linked_objects": [],
    "linkedObjectsIds": None,
    "oldref": None,
    "fk_project": None,
    "contact_id": None,
    "user": None,
    "origin": None,
    "origin_id": None,
    "ref": "TESTTEST",
    "ref_ext": "TESTTEST",
    "statut": "2",
    "status": "2",
    "country_id": None,
    "country_code": None,
    "state_id": None,
    "region_id": None,
    "mode_reglement_id": "6",
    "cond_reglement_id": "1",
    "demand_reason_id": None,
    "transport_mode_id": None,
    "shipping_method_id": None,
    "shipping_method": None,
    "multicurrency_code": None,
    "multicurrency_tx": "1.00000000",
    "model_pdf": "sponge",
    "last_main_doc": "",
    "fk_bank": None,
    "fk_account": "3",
    "note_public": "",
    "note_private": "--＊8800",
    "total_ht": "1.00000000",
    "total_tva": "0.00000000",
    "total_localtax1": "0.00000000",
    "total_localtax2": "0.00000000",
    "total_ttc": "1.00000000",
    "lines": [
    ],
    "name": None,
    "lastname": None,
    "firstname": None,
    "civility_id": None,
    "date_creation": 1699205524,
    "date_validation": 1699142400,
    "date_modification": 1700646892,
    "date_update": None,
    "date_cloture": None,
    "user_author": "4",
    "user_creation": None,
    "user_creation_id": None,
    "user_valid": None,
    "user_validation": None,
    "user_validation_id": None,
    "user_closing_id": None,
    "user_modification": None,
    "user_modification_id": None,
    "specimen": 0,
    "labelStatus": None,
    "showphoto_on_popup": None,
    "nb": [],
    "output": None,
    "extraparams": [],
    "type": "0",
    "subtype": None,
    "totalpaid": 590,
    "totaldeposits": None,
    "totalcreditnotes": None,
    "sumpayed": "590.00000000",
    "sumpayed_multicurrency": None,
    "sumdeposit": None,
    "sumdeposit_multicurrency": None,
    "sumcreditnote": None,
    "sumcreditnote_multicurrency": None,
    "remaintopay": "0",
    "fk_incoterms": None,
    "label_incoterms": None,
    "location_incoterms": None,
    "brouillon": None,
    "socid": "15",
    "fk_user_author": "4",
    "fk_user_valid": None,
    "fk_user_modif": None,
    "date": 1699142400,
    "datem": 1700646892,
    "date_livraison": None,
    "delivery_date": None,
    "ref_client": None,
    "ref_customer": None,
    "remise_absolue": "0",
    "remise_percent": "0",
    "revenuestamp": "0.00000000",
    "resteapayer": None,
    "close_code": None,
    "close_note": None,
    "paye": "1",
    "module_source": None,
    "pos_source": None,
    "fk_fac_rec_source": None,
    "fk_facture_source": None,
    "date_lim_reglement": 1699142400,
    "cond_reglement_code": "RECEP",
    "cond_reglement_doc": "Due upon receipt",
    "mode_reglement_code": "CB",
    "line": None,
    "fac_rec": None,
    "date_pointoftax": "",
    "fk_multicurrency": None,
    "multicurrency_total_ht": "0.00000000",
    "multicurrency_total_tva": "0.00000000",
    "multicurrency_total_ttc": "0.00000000",
    "situation_cycle_ref": None,
    "situation_counter": None,
    "situation_final": None,
    "tab_previous_situation_invoice": [],
    "tab_next_situation_invoice": [],
    "retained_warranty": None,
    "retained_warranty_date_limit": "",
    "retained_warranty_fk_cond_reglement": None
}

blank_line = {
        "module": None,
        "id": "274",
        "entity": None,
        "import_key": None,
        "array_options": [],
        "array_languages": None,
        "contacts_ids": None,
        "linked_objects": None,
        "linkedObjectsIds": None,
        "oldref": None,
        "origin": None,
        "origin_id": None,
        "ref": "Bacon_Egg_Cheese_Biscuit",
        "ref_ext": None,
        "statut": None,
        "status": None,
        "state_id": None,
        "region_id": None,
        "demand_reason_id": None,
        "transport_mode_id": None,
        "shipping_method": None,
        "multicurrency_tx": None,
        "last_main_doc": None,
        "fk_bank": None,
        "fk_account": None,
        "total_ht": "250.00000000",
        "total_tva": "0.00000000",
        "total_localtax1": "0.00000000",
        "total_localtax2": "0.00000000",
        "total_ttc": "250.00000000",
        "lines": None,
        "date_creation": None,
        "date_validation": None,
        "date_modification": None,
        "date_update": None,
        "date_cloture": None,
        "user_author": None,
        "user_creation": None,
        "user_creation_id": None,
        "user_valid": None,
        "user_validation": None,
        "user_validation_id": None,
        "user_closing_id": None,
        "user_modification": None,
        "user_modification_id": None,
        "specimen": 0,
        "labelStatus": None,
        "showphoto_on_popup": None,
        "nb": [],
        "output": None,
        "extraparams": [],
        "rowid": "274",
        "fk_unit": None,
        "date_debut_prevue": None,
        "date_debut_reel": None,
        "date_fin_prevue": None,
        "date_fin_reel": None,
        "weight": None,
        "weight_units": None,
        "width": None,
        "width_units": None,
        "height": None,
        "height_units": None,
        "length": None,
        "length_units": None,
        "surface": None,
        "surface_units": None,
        "volume": None,
        "volume_units": None,
        "multilangs": None,
        "product_type": "0",
        "fk_product": "2",
        "desc": "Bacon Egg and Cheese $250.0",
        "description": "Bacon Egg and Cheese $250.0",
        "product": None,
        "product_ref": "Bacon_Egg_Cheese_Biscuit",
        "product_label": "Bacon Egg Cheese Biscuit",
        "product_barcode": None,
        "product_desc": "",
        "fk_product_type": "0",
        "qty": "1",
        "duree": None,
        "remise_percent": "0",
        "info_bits": "0",
        "special_code": "0",
        "subprice": None,
        "tva_tx": "0.0000",
        "label": None,
        "libelle": "Bacon Egg Cheese Biscuit",
        "price": None,
        "vat_src_code": None,
        "localtax1_tx": "0.0000",
        "localtax2_tx": "0.0000",
        "localtax1_type": None,
        "localtax2_type": None,
        "remise": None,
        "date_start_fill": None,
        "date_end_fill": None,
        "buy_price_ht": None,
        "buyprice": None,
        "pa_ht": "0.00000000",
        "marge_tx": "",
        "marque_tx": "",
        "multicurrency_subprice": "0.00000000",
        "multicurrency_total_ht": "0.00000000",
        "multicurrency_total_tva": "0.00000000",
        "multicurrency_total_ttc": "0.00000000",
        "fk_user_author": None,
        "fk_user_modif": None,
        "fk_accounting_account": "0",
        "fk_facture": "731",
        "fk_parent_line": None,
        "fk_remise_except": None,
        "rang": "0",
        "fk_fournprice": None,
        "fk_code_ventilation": 0,
        "date_start": 1699205524,
        "date_end": 1699205524,
        "situation_percent": "100",
        "fk_prev_id": None,
        "code_ventilation": "0"
}
with open(input_csv, newline='') as csvin:
    with open(invoices_csv, 'a+', newline='') as invoicescsv:
        inreader = csv.reader(csvin, delimiter=',')
        invoicewriter = csv.writer(
            invoicescsv,
            delimiter=',',
            quotechar='|',
            quoting=csv.QUOTE_MINIMAL
        )
        invoicewriter.writerow([
            'Invoice ref.* (f.ref)',
            'Ref. extern (f.ref_ext)',
            'Customer* (f.fk_soc)',
            'Invoice creation date (f.datec)',
            'Invoice date (f.datef)',
            'Validation Date (f.date_valid)',
            'Invoice paid (f.paye)',
            'RemisePercent (f.remise_percent)',
            'RemiseAbsolue (f.remise_absolue)',
            'Remise (f.remise)',
            'Total tax (f.total_tva)',
            'Total (excl. tax) (f.total_ht)',
            'Total (inc. tax) (f.total_ttc)',
            'Invoice status (f.fk_statut)',
            'Modifier Id (f.fk_user_modif)',
            'Validator Id (f.fk_user_valid)',
            'Closer Id (f.fk_user_closing)',
            'Invoice Source Id (f.fk_facture_source)',
            'Project Id (f.fk_projet)',
            'Bank Account (f.fk_account)',
            'Currency* (f.fk_currency)',
            'Payment Condition (f.fk_cond_reglement)',
            'Payment Mode (f.fk_mode_reglement)',
            'Payment due on (f.date_lim_reglement)',
            'Invoice note (f.note_public)',
            'Doc template (f.model_pdf)',
        ])
        next(inreader, None)
        for row in inreader:
            invoicewriter.writerow([
                # Receipt number > 'Invoice ref.* (f.ref)',
                row[1],
                # Receipt number > 'Ref. extern (f.ref_ext)',
                row[1],
                # Order Type > 'Customer* (f.fk_soc)',
                customer_type.get(row[7].strip(), None),
                # payment time > 'Invoice creation date (f.datec)',
                row[3],
                # payment time > 'Invoice date (f.datef)',
                row[3],
                # payment time > 'Validation Date (f.date_valid)',
                row[3],
                # 'Invoice paid (f.paye)',
                1,
                # 'RemisePercent (f.remise_percent)',
                0,
                # 'RemiseAbsolue (f.remise_absolue)',
                0,
                # 'Remise (f.remise)',
                0,
                # 'Total tax (f.total_tva)',
                0,
                # payment amount > 'Total (excl. tax) (f.total_ht)',
                row[12],
                # payment amount >'Total (inc. tax) (f.total_ttc)',
                row[12],
                # 'Invoice status (f.fk_statut)',
                1,
                # 'Modifier Id (f.fk_user_modif)',
                None,
                # 'Validator Id (f.fk_user_valid)',
                None,
                # 'Closer Id (f.fk_user_closing)',
                None,
                # 'Invoice Source Id (f.fk_facture_source)',
                None,
                # 'Project Id (f.fk_projet)',
                None,
                # 'Bank Account (f.fk_account)',
                bank_account.get(row[13].strip(), None),
                # 'Currency* (f.fk_currency)',
                'TWD',
                # 'Payment Condition (f.fk_cond_reglement)',
                'RECEP',
                # 'Payment Mode (f.fk_mode_reglement)',
                # Even line pay is cash because it's a direct transfer
                4,
                # payment time > 'Payment due on (f.date_lim_reglement)',
                row[3],
                # items > 'Invoice note (f.note_public)',
                row[20],
                # 'Doc template (f.model_pdf)',
                'sponge',
            ])
